Fix E2E test pipeline which checks master branch
Signed-off-by: Dmytro Nochevnov <dnochevn@redhat.com>

diff --git a/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile b/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
--- a/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
+++ b/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile
@@ -221,50 +221,48 @@ pipeline {
                         # sed -i "s/selfSignedCert: false/selfSignedCert: true/" $CUSTOM_RESOURCE_FILE_PATH    
                     """
 
-                    retry(2) {
-                        echo "Install Che"
-                        sh """
-                            ${WORKSPACE}/chectl server:start \\
-                            --k8spodreadytimeout=180000 \\
-                            --installer=operator \\
-                            --listr-renderer=verbose \\
-                            --platform=minikube \\
-                            --che-operator-cr-yaml=$CUSTOM_RESOURCE_FILE_PATH
-                        """
+                    echo "Install Che"
+                    sh """
+                        ${WORKSPACE}/chectl server:start \\
+                        --k8spodreadytimeout=180000 \\
+                        --installer=operator \\
+                        --listr-renderer=verbose \\
+                        --platform=minikube \\
+                        --che-operator-cr-yaml=$CUSTOM_RESOURCE_FILE_PATH
+                    """
 
-                        cheHost = sh(
-                                script: "kubectl get ingress che -n=che -o=jsonpath={'.spec.rules[0].host'}",
-                                returnStdout: true
-                        ).trim()
+                    cheHost = sh(
+                            script: "kubectl get ingress che -n=che -o=jsonpath={'.spec.rules[0].host'}",
+                            returnStdout: true
+                    ).trim()
 
-                        echo "Wait che-server to be available"
-                        sh """
-                             COUNTER=0;
-                             SUCCESS_RATE_COUNTER=0;
-                             while true; do
-                              if [ \$COUNTER -gt 180 ]; then
-                              echo "Unable to get stable route. Exiting"
-                                exit 1
-                              fi
-                              
-                              ((COUNTER+=1))
-                              
-                              
-                              STATUS_CODE=\$(curl -k -sL -w "%{http_code}" -I http://${cheHost} -o /dev/null; true) || true
-                              
-                              echo "Try \${COUNTER}. Status code: \${STATUS_CODE}"
-                              if [ "\$STATUS_CODE" == "200" ]; then 
-                                ((SUCCESS_RATE_COUNTER+=1))
-                              fi
-                              sleep 1;
+                    echo "Wait che-server to be available"
+                    sh """
+                            COUNTER=0;
+                            SUCCESS_RATE_COUNTER=0;
+                            while true; do
+                            if [ \$COUNTER -gt 180 ]; then
+                            echo "Unable to get stable route. Exiting"
+                            exit 1
+                            fi
                             
-                              if [ \$SUCCESS_RATE_COUNTER == \$SUCCESS_THRESHOLD ]; then 
-                                echo "Route is stable enough. Continuing running tests"
-                                break
-                              fi
-                             done
-                        """
-                    }
+                            ((COUNTER+=1))
+                            
+                            
+                            STATUS_CODE=\$(curl -k -sL -w "%{http_code}" -I http://${cheHost} -o /dev/null; true) || true
+                            
+                            echo "Try \${COUNTER}. Status code: \${STATUS_CODE}"
+                            if [ "\$STATUS_CODE" == "200" ]; then 
+                            ((SUCCESS_RATE_COUNTER+=1))
+                            fi
+                            sleep 1;
+                        
+                            if [ \$SUCCESS_RATE_COUNTER == \$SUCCESS_THRESHOLD ]; then 
+                            echo "Route is stable enough. Continuing running tests"
+                            break
+                            fi
+                            done
+                    """
                 }
             }
         }
@@ -378,6 +376,8 @@ pipeline {
 
                 env > $LOGS_AND_CONFIGS/env.output.txt || true
                 ${WORKSPACE}/chectl --help > $LOGS_AND_CONFIGS/chectl.version.txt || true
+
+                cp -r /tmp/chectl-logs $LOGS_AND_CONFIGS || true
             """
 
             archiveArtifacts allowEmptyArchive: true, artifacts: "tests/e2e/report/**, logs-and-configs/**"
