Stabilize installation of dependencies in PR check Happy path testing pipelines (#19336)
Signed-off-by: Dmytro Nochevnov <dnochevn@redhat.com>

diff --git a/tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile b/tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
--- a/tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
+++ b/tests/.infra/crw-ci/dashboard-next/pr-check/Jenkinsfile
@@ -1,7 +1,7 @@
 #!groovy
 
 pipeline {
-    agent { label "minikube-rhel7-24gb" }
+    agent { label "minikube-rhel7-16gb" }
 
     options {
         timestamps()
@@ -142,15 +142,20 @@ pipeline {
                         echo "Install dependencies needed for build of Eclipse Che"
                         sh """
                             # workaround https://github.com/eclipse/che/issues/19093
-                            for i in {1..30} 
+                            for i in {1..100} 
                             do
                                 echo "-- ATTEMPT \$i --"
                                 sudo yum install -y glibc.i686 libfontconfig.so.1 libstdc++-devel.i686 \\
-                                    --disablerepo=rhel-7-server-extras-os-rpms,rhel-7-server-ose-3.4-os-rpms,rhel-7-server-optional-os-rpms || true
+                                    --disablerepo=rhel-7-server-extras-os-rpms,rhel-7-server-ose-3.4-os-rpms,rhel-7-server-optional-os-rpms,rhel-7-server-supplementary-os-rpms || true
                                 
                                 sudo yum list installed | grep "glibc.i686" && sudo yum list installed | grep "fontconfig.i686" && sudo yum list installed | grep "libstdc++-devel.i686" && break
                                 
-                                sleep 5
+                                sleep 10
+                                
+                                if [ "\$i" -gt "100" ]; then 
+                                    echo "Can't install dependencies."
+                                    exit 1
+                                fi
                             done
                         """
 
