chore: enable Trusted Publishing
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

diff --git a/.github/workflows/typescript-publish.yml b/.github/workflows/typescript-publish.yml
--- a/.github/workflows/typescript-publish.yml
+++ b/.github/workflows/typescript-publish.yml
@@ -7,10 +7,19 @@
 # SPDX-License-Identifier: EPL-2.0
 #
 
-name: Publish Next Che E2E Tests to npmjs
+name: Build/Publish Next Che E2E Tests to npmjs
 
 on:
   workflow_dispatch:
+    inputs:
+      release-version:
+        description: 'release version in format 7.y.z'
+        required: true
+      release-remake:
+        description: 'set to true to recreate existing tags (otherwise release will fail if tags already exist)'
+        type: boolean
+        default: false
+        required: true
   push:
     branches: 
       - main
@@ -23,6 +32,35 @@ jobs:
   publish:
     runs-on: ubuntu-22.04
     steps:
+    - name: Validate parameters and build type
+      shell: bash
+      id: dist-tag-eval
+      run: |
+        # check if workflow is triggered manually (release) or via branch push (next build)
+        # release will always be performed as workflow_dispatch trigger, while push triggers are for dev/next builds
+        # based on this information, we determine the dist-tag for pushing to npmjs
+        DIST_TAG=
+        if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
+          RELEASE_VERSION=${{ github.event.inputs.release-version }}
+          if [[ "$RELEASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "[INFO]" preparing to build and release with version: $RELEASE_VERSION
+            # DIST_TAG is not used in make-release.sh, as release version will always be latest anyway
+            DIST_TAG=latest
+          else
+            echo "[ERROR] incorrect version "$RELEASE_VERSION". Must be following format <number>.<number>.<number>, e.g. 7.111.0"
+            exit 1
+          fi
+        fi
+        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
+          if [[ ${GITHUB_REF##*/} == "7."**".x" ]]; then
+            echo "[INFO] using ${GITHUB_REF##*/} tag"
+            DIST_TAG="next-${GITHUB_REF##*/}"
+          else
+            echo "[INFO] using "next" tag"
+            DIST_TAG=next
+          fi
+        fi
+        echo "npm_dist_tag=$DIST_TAG" >> $GITHUB_OUTPUT
     - uses: actions/setup-node@v3
       with:
         node-version: '16'
@@ -32,24 +70,82 @@ jobs:
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
-    - name: publish
+    - name: Check existing release tags
+      if: github.event_name == 'workflow_dispatch'
       env:
-        NODE_AUTH_TOKEN: ${{secrets.CHE_NPM_AUTH_TOKEN}}
+        GITHUB_TOKEN: ${{secrets.CHE_BOT_GITHUB_TOKEN}}
       run: |
-        if [[ ${GITHUB_REF##*/} == "7."**".x" ]]; then
-          echo "[INFO] using ${GITHUB_REF##*/} tag"
-          DIST_TAG=next-${GITHUB_REF##*/}
+        set +e
+        RECREATE_TAGS=${{ github.event.inputs.release-remake }}
+        VERSION=${{ github.event.inputs.release-version }}
+        EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
+        if [[ -n ${EXISTING_TAG} ]]; then
+          if [[ ${RECREATE_TAGS} == "true" ]]; then
+            echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
+            git push origin :${VERSION}
+          else
+            echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
+            exit 1
+          fi
         else
-          echo "[INFO] using "next" tag"
-          DIST_TAG=next
+          echo "[INFO] No existing tags detected for ${VERSION}"
         fi
+    - name: "Set up QEMU"
+      if: github.event.inputs.release-version == 'true'
+      uses: docker/setup-qemu-action@v2
+    - name: "Docker quay.io Login"
+      if: github.event.inputs.release-version == 'true'
+      uses: docker/login-action@v2
+      with:
+        registry: quay.io
+        username: ${{ secrets.QUAY_USERNAME }}
+        password: ${{ secrets.QUAY_PASSWORD }}
+    - name: Login to docker.io
+      if: github.event.inputs.release-version == 'true'
+      uses: docker/login-action@v2
+      with:
+        registry: docker.io
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    - name: Set up yq
+      if: github.event.inputs.release-version == 'true'
+      run: |
+        sudo wget https://github.com/mikefarah/yq/releases/download/v4.7.0/yq_linux_amd64 -O /usr/bin/yq
+        sudo chmod +x /usr/bin/yq
+    - name: Perform a release
+      if: github.event.inputs.release-version == 'true'
+      run: |
+        git config --global user.name "Mykhailo Kuznietsov"
+        git config --global user.email "mkuznets@redhat.com"
+        git config --global pull.rebase true
 
+        export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
+        ./make-release.sh --version ${{ github.event.inputs.version}}
+    - name: Build and publish next version
+      if: github.event_name == 'push'
+      run: |
         cd tests/e2e
-        npm ci && npm run tsc
 
         SHORT_SHA1=$(git rev-parse --short=7 HEAD)
         CURRENT_VERSION=$(sed -r 's/(.*)-next/\1/' ../../VERSION)
         NEW_VERSION="${CURRENT_VERSION}-next-${SHORT_SHA1}"
         sed -i -r -e "s/(\"version\": )(\".*\")/\1\"$NEW_VERSION\"/" package.json
 
-        npm publish --tag $DIST_TAG
+        npm ci && npm run tsc
+
+        # uncomment this publishing, when steps below are removed
+        #npm publish ${{ steps.dist-tag-eval.outputs.npm_dist_tag }} 
+
+    # newer npm version is required for Trusted publishing
+    # remove the steps of npm below, once build will be updated to newer version
+    - name: Change node version for publishing
+      uses: actions/setup-node@v3
+      with:
+        node-version: '24'
+        registry-url: 'https://registry.npmjs.org'
+        scope: '@eclipse-che'
+    - name: Publish
+      run: |
+        cd tests/e2e
+        # --ignore-scripts parameter is needed to prevent recompilation
+        npm publish --ignore-scripts --tag ${{ steps.dist-tag-eval.outputs.npm_dist_tag }} 
